project:
  type: website
  output-dir: ../

website:
  title: "Florian Lecorvaisier's website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: blog.qmd
        text: My blog
        
format:
  html:
    theme:
      - darkly
      - brand
    css: styles.css
    toc: true
    header-includes: |
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">

mainfont: Ubuntu

editor: visual

